version: "3.9"

services:
  astro:
    build:
      context: .
      dockerfile: Dockerfile
    image: astro-app:prod
    container_name: astro-ssr
    restart: unless-stopped
    ports:
      - "4321:4321"
    environment:
      POD_NAME: test-1
      NODE_ENV: production
      APP_ENV: prod
      HOST: 0.0.0.0
      PORT: 4321
    # 如果你要把容器日志写到文件目录（例如 /app/logs），可以打开下面两行：
    volumes:
      - ./logs:/app/logs
